site_name: CSCS netstack
site_url: https://eth-cscs.github.io/netstack

# provide a link to the docs in top RHS corner
repo_url: https://github.com/eth-cscs/netstack
# provide a link to "edit this page" to each page
edit_uri: edit/main/docs/
extra_css:
  - stylesheets/extra.css
plugins:
  - search:
      pipeline:
        - trimmer
  - autorefs
nav:
  - Welcome: index.md
  - Tools: tools.md
  - Environment variables: envvars.md
  - 'Packages':
    - packages/index.md
    - 'MPI':
      - 'cray-mpich': packages/cray-mpich.md
      - 'cray-gtl': packages/cray-gtl.md
      - 'mpich': packages/mpich.md
      - 'openmpi': packages/openmpi.md
    - 'Fabric / Slingshot':
      - 'libfabric': packages/libfabric.md
      - 'libcxi': packages/libcxi.md
      - 'cxi-driver': packages/cxi-driver.md
      - 'cassini-headers': packages/cassini-headers.md
    - 'GPU communication':
      - 'nccl': packages/nccl.md
      - 'aws-ofi-nccl': packages/aws-ofi-nccl.md
      - 'cuda': packages/cuda.md
      - 'cuda-driver': packages/cuda-driver.md
    - 'Intra-node':
      - 'xpmem': packages/xpmem.md
    - 'Launch':
      - 'cray-pmi': packages/cray-pmi.md
      - 'cray-pals': packages/cray-pals.md
      - 'slurm': packages/slurm.md

theme:
  name: material
  variant: classic
  language: en
  features:
    - content.code.copy
    # add an "edit this page" icon on each page
    - content.action.edit
    - navigation.indexes
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.top
    - content.code.annotate
  icon:
    # set the icon for "edit this page"
    edit: material/pencil
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/cscs-logo.png
  font:
    text: Roboto
    code: Roboto Mono
  custom_dir: overrides
markdown_extensions:
  - admonition
  - def_list
  - markdown.extensions.smarty
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  # for captioning images
  - pymdownx.blocks.caption
